version: "3"
services:
  backend:
    image: muratisiklan/backend:latest
    ports:
      - 8000:8000
    env_file:
      - ./.env.backend
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    env_file:
      - ./.env.postgres
  mlservice:
    image: muratisiklan/mlservice:latest
    ports:
      - 8080:8080
    depends_on:
      - mongo
    env_file:
      - ./.env.mlservice
  mongo:
    image: mongo:latest
