services:
  backend:
#    image: muratisiklan/backend:latest
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.backend
    depends_on:
      - postgres
      - mlservice
  postgres:
    image: postgres:latest
    env_file:
      - ./.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mlservice:
#    image: muratisiklan/mlservice:latest
    build: ./mlservice
    ports:
      - 8080:8080
    depends_on:
      - mongo
    env_file:
      - ./.env.mlservice
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
