version: "3"
services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    env_file:
        - ./.env.backend
    depends_on:
      - postgres
  postgres:
    image: postgres
    env_file:
        - ./.env.postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
  mongo:
    image: mongo
    env_file:
      - ./.env.mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/var/lib/mongodb/data

volumes:
  postgres-db: