services:
  mlservice:
#    image: muratisiklan/mlservice:latest
    build: ./mlservice
    ports:
      - 8080:8080
    depends_on:
      - mongo
    env_file:
      - ./.env.mlservice
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
