name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "mlservice/**"

jobs:
  build-and-push-backend:
    if: ${{ github.event_name == 'push' && (github.event.head_commit.message != '' || github.event.head_commit.added || github.event.head_commit.modified || github.event.head_commit.deleted) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest

  build-and-push-mlservice:
    if: ${{ github.event_name == 'push' && (github.event.head_commit.message != '' || github.event.head_commit.added || github.event.head_commit.modified || github.event.head_commit.deleted) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push mlservice image
        uses: docker/build-push-action@v5
        with:
          context: ./mlservice
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlservice:latest
